// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"tammy/ent/predicate"
	"tammy/ent/useremail"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserEmailDelete is the builder for deleting a UserEmail entity.
type UserEmailDelete struct {
	config
	hooks    []Hook
	mutation *UserEmailMutation
}

// Where appends a list predicates to the UserEmailDelete builder.
func (ued *UserEmailDelete) Where(ps ...predicate.UserEmail) *UserEmailDelete {
	ued.mutation.Where(ps...)
	return ued
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ued *UserEmailDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ued.hooks) == 0 {
		affected, err = ued.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserEmailMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ued.mutation = mutation
			affected, err = ued.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ued.hooks) - 1; i >= 0; i-- {
			if ued.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ued.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ued.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ued *UserEmailDelete) ExecX(ctx context.Context) int {
	n, err := ued.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ued *UserEmailDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: useremail.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: useremail.FieldID,
			},
		},
	}
	if ps := ued.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ued.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// UserEmailDeleteOne is the builder for deleting a single UserEmail entity.
type UserEmailDeleteOne struct {
	ued *UserEmailDelete
}

// Exec executes the deletion query.
func (uedo *UserEmailDeleteOne) Exec(ctx context.Context) error {
	n, err := uedo.ued.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{useremail.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uedo *UserEmailDeleteOne) ExecX(ctx context.Context) {
	uedo.ued.ExecX(ctx)
}
